# NumPy: the absolute basics for beginners

## How to import NumPy

In [99]:
import numpy as np

## Array fundamentals

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [100]:
a = np.array([1, 2, 3, 4, 5, 6])

In [102]:
a

array([10,  2,  3,  4,  5,  6])

In [103]:
a[0]

np.int64(10)

In [104]:
b = a[3:]
b

array([4, 5, 6])

In [107]:
b = a[3:]
b

array([4, 5, 6])

## Array attributes

In [109]:
a.ndim

2

In [110]:
a.shape

(3, 4)

In [111]:
len(a.shape) == a.ndim

True

In [108]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a[1, 3]

np.int64(8)

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('ndim:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('dtype:', a.dtype)

ndim: 2
shape: (3, 4)
size: 12
dtype: int64


In [14]:
import math
a.size == math.prod(a.shape)

True

In [112]:
a.dtype

dtype('int64')

## How to create a basic array

In [15]:
np.zeros(2)

array([0., 0.])

In [16]:
np.ones(2)

array([1., 1.])

In [17]:
# Create an empty array with 2 elements
np.empty(2)  # may vary

array([1., 1.])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
# arange with step size
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [20]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
# Specifying data type
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

## Adding, removing, and sorting elements

In [22]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
# Concatenate 1D arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# Concatenate 2D arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?


In [25]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])

print('ndim:', array_example.ndim)
print('size:', array_example.size)
print('shape:', array_example.shape)

ndim: 3
size: 24
shape: (3, 2, 4)


## Can you reshape an array?

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [27]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [28]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

## How to convert a 1D array into a 2D array

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
print('original shape:', a.shape)

a2 = a[np.newaxis, :]
print('after newaxis:', a2.shape)

original shape: (6,)
after newaxis: (1, 6)


In [30]:
# Row vector
row_vector = a[np.newaxis, :]
print('row vector shape:', row_vector.shape)

# Column vector
col_vector = a[:, np.newaxis]
print('col vector shape:', col_vector.shape)

row vector shape: (1, 6)
col vector shape: (6, 1)


In [31]:
# Using expand_dims
b = np.expand_dims(a, axis=1)
print('expand_dims axis=1:', b.shape)

c = np.expand_dims(a, axis=0)
print('expand_dims axis=0:', c.shape)

expand_dims axis=1: (6, 1)
expand_dims axis=0: (1, 6)


## Indexing and slicing

In [32]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [33]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Elements less than 5
print(a[a < 5])

[1 2 3 4]


In [34]:
# Elements >= 5
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [35]:
# Divisible by 2
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [36]:
# Two conditions with & operator
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [37]:
# Boolean array with | operator
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [38]:
# np.nonzero
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [39]:
# List of coordinates where elements exist
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [40]:
print(a[b])

[1 2 3 4]


In [41]:
# Element not in array
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data

In [42]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [43]:
# vstack
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [44]:
# hstack
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [45]:
# hsplit
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [47]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [48]:
# view (shallow copy)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1[0] = 99
print('b1:', b1)
print('a (also modified):', a)

b1: [99  2  3  4]
a (also modified): [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
# copy (deep copy)
b2 = a.copy()

## Basic array operations

In [50]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print('add:', data + ones)
print('subtract:', data - ones)
print('multiply:', data * data)
print('divide:', data / data)

add: [2 3]
subtract: [0 1]
multiply: [1 4]
divide: [1. 1.]


In [51]:
# sum
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [52]:
# sum along axis
b = np.array([[1, 1], [2, 2]])
print('sum axis=0 (rows):', b.sum(axis=0))
print('sum axis=1 (cols):', b.sum(axis=1))

sum axis=0 (rows): [3 3]
sum axis=1 (cols): [2 4]


## Broadcasting

In [53]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

## More useful array operations

Covers: `max`, `min`, `sum`, `mean`, `prod`, `std`

In [54]:
data = np.array([1, 2, 3])
print('max:', data.max())
print('min:', data.min())
print('sum:', data.sum())

max: 3
min: 1
sum: 6


In [55]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print('sum:', a.sum())
print('min:', a.min())
print('min per column (axis=0):', a.min(axis=0))

sum: 4.8595784
min: 0.05093587
min per column (axis=0): [0.12697628 0.05093587 0.26590556 0.5510652 ]


## Creating matrices

In [56]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
# Matrix indexing
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [58]:
# Matrix aggregation
print('max:', data.max())
print('min:', data.min())
print('sum:', data.sum())

max: 6
min: 1
sum: 21


In [59]:
# Aggregation with axis
data = np.array([[1, 2], [5, 3], [4, 6]])
print('max axis=0:', data.max(axis=0))
print('max axis=1:', data.max(axis=1))

max axis=0: [5 6]
max axis=1: [2 5 6]


In [60]:
# Matrix arithmetic
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [61]:
# Broadcasting with matrices
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [62]:
# N-dimensional array printing
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [63]:
# ones, zeros, random
rng = np.random.default_rng()
print(np.ones(3))
print(np.zeros(3))
print(rng.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.3173239  0.09642092 0.77003441]


In [64]:
# 2D ones, zeros, random
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.35221639 0.94000094]
 [0.05965842 0.41897172]
 [0.54667844 0.86829454]]


## Generating random numbers

In [65]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))  # may vary

array([[1, 3, 4, 2],
       [3, 3, 0, 4]])

## How to get unique items and counts

Covers: `np.unique()`

In [66]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [67]:
# Unique values with indices
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [68]:
# Unique values with counts
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [69]:
# Unique in 2D array
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [70]:
# Unique rows
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
# Unique rows with index and count
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
print('unique rows:', unique_rows)
print('indices:', indices)
print('occurrence count:', occurrence_count)

unique rows: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
indices: [0 1 2]
occurrence count: [2 1 1]


## Transposing and reshaping a matrix

Covers: `arr.reshape()`, `arr.transpose()`, `arr.T`

In [72]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [73]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [75]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

## How to reverse an array

Covers: `np.flip()`

In [76]:
# Reversing a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array:', reversed_arr)

Reversed Array: [8 7 6 5 4 3 2 1]


In [77]:
# Reversing a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr = np.flip(arr_2d)
print('Fully reversed:\n', reversed_arr)

Fully reversed:
 [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [78]:
# Reverse only rows
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [79]:
# Reverse only columns
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [80]:
# Reverse a single row
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [81]:
# Reverse a single column
arr_2d[:, 1] = np.flip(arr_2d[:, 1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## Reshaping and flattening multidimensional arrays

Covers: `.flatten()`, `.ravel()`

In [82]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
# flatten: changes don't affect original
a1 = x.flatten()
a1[0] = 99
print('original x:', x)
print('flattened a1:', a1)

original x: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
flattened a1: [99  2  3  4  5  6  7  8  9 10 11 12]


In [84]:
# ravel: changes DO affect original
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a2 = x.ravel()
a2[0] = 98
print('original x (modified):', x)
print('raveled a2:', a2)

original x (modified): [[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
raveled a2: [98  2  3  4  5  6  7  8  9 10 11 12]
